source 'https://rubygems.org'

gem 'ffi','1.9.3'
gem 'terminal-table','1.4.5'
gem 'gooddata'
gem 'twitter'
gem 'gooddata_connectors_base', :path => 'gooddata_connectors_base-s3'
gem 'gooddata_connectors_metadata', :path => 'gooddata_connectors_metadata-0.0.9'
gem 'gooddata_connectors_downloader_twitter', :path => 'gooddata_connectors_downloader_twitter-master'